import Head from "next/head";

import { Section1Home } from "../components/Home/sections/section1";
import { Section2Home } from "../components/Home/sections/section2";
import { Section3Home } from "../components/Home/sections/section3";

export default function Home() {
  return (
    <>
      <Head>
        <title>Top Sistema de Ensino</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Section1Home />
      <Section2Home />
      <Section3Home />
    </>
  );
}
